//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CharacterSheetLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CharacterSheetLocale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Models.Localization.CharacterSheetLocale", typeof(CharacterSheetLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to he.
        /// </summary>
        public static string He {
            get {
                return ResourceManager.GetString("He", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to her.
        /// </summary>
        public static string Her {
            get {
                return ResourceManager.GetString("Her", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hers.
        /// </summary>
        public static string Hers {
            get {
                return ResourceManager.GetString("Hers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to him.
        /// </summary>
        public static string Him {
            get {
                return ResourceManager.GetString("Him", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to his.
        /// </summary>
        public static string His {
            get {
                return ResourceManager.GetString("His", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to she.
        /// </summary>
        public static string She {
            get {
                return ResourceManager.GetString("She", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to theirs.
        /// </summary>
        public static string Theirs {
            get {
                return ResourceManager.GetString("Theirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to them.
        /// </summary>
        public static string Them {
            get {
                return ResourceManager.GetString("Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to they.
        /// </summary>
        public static string They {
            get {
                return ResourceManager.GetString("They", resourceCulture);
            }
        }
    }
}
